"""Take a new clip from an mp4 to a runnable configuration."""

from __future__ import annotations

import math
from pathlib import Path

__all__ = ["onboarding_checklist", "scaffold_config", "suggest_anchor_frames"]


def suggest_anchor_frames(frame_count: int, max_gap: int = 100) -> list[int]:
    """Evenly spaced anchor frames covering the clip, every gap <= ``max_gap``."""
    if frame_count < 2:
        raise ValueError(f"need at least 2 frames to place anchors, got {frame_count}")
    last = frame_count - 1
    n_gaps = max(1, math.ceil(last / max_gap))
    return [round(i * last / n_gaps) for i in range(n_gaps + 1)]


def scaffold_config(video: str | Path, fps: float) -> str:
    """A loadable config for one clip; every path in it is derived from the video's stem."""

    stem = Path(video).stem
    return f"""\
# {stem} — generated by scripts/new_clip.py. Self-contained by design: a run must
# be reproducible from this file alone.
device: auto

io:
  input_video: {video}
  output_dir: outputs/{stem}
  auto_letterbox: true
  letterbox_threshold: 20.0
  crop_top: 0
  crop_bottom: 0
  crop_left: 0
  crop_right: 0
  frame_start: 0
  frame_stop: null
  frame_stride: 1

detection:
  weights: weights/detection/detect-tactical-v3.pt
  imgsz: 1280
  conf: 0.25
  iou: 0.7
  max_det: 300
  ball_conf: null
  agnostic_nms: true

homography:
  mask_margin_m: 1.0

# Pitch dimensions in metres. The Laws of the Game permit 100-110 x 64-75, and wrong
# values here do not error -- they silently rescale every projected distance, speed,
# possession radius, and the radar. Set them from the venue when you know it.
pitch:
  length: 105.0
  width: 68.0

tracking:
  calibration_path: outputs/{stem}/calibration.npz
  mask_margin_m: 1.0
  mask_margin_referee_m: 3.0
  min_conf: 0.1
  track_high_thresh: 0.5
  track_low_thresh: 0.1
  new_track_thresh: 0.6
  match_thresh: 0.8
  track_buffer: 30

ball:
  enabled: true
  weights: weights/detection/detect-ball-ft-v1.pt
  roi_size: 640
  roi_imgsz: 640
  roi_conf: 0.10
  roi_max_coast: 45
  merge_dist_px: 20.0
  mask_margin_m: 6.0
  min_box_px: 4.0
  max_box_px: 40.0
  q_pos: 1.0
  q_vel: 0.5
  r_px: 5.0
  gate_chi2: 9.21
  max_gap: 60
  max_speed_px: 40.0
  miss_cost: 0.3
  conf_weight: 0.2
  speed_weight: 0.1
  max_interp_gap: 30
  airborne_window: 31
  airborne_min_frames: 18
  airborne_curvature_min: 0.05
  airborne_residual_px: 3.0
  airborne_speed_ms: 25.0

projection:
  smooth_window: 15
  fps: {fps}
  scale_px_per_m: 10.0
  margin_px: 40
  possession:
    radius_m: 2.0
    acquire_frames: 12
    max_ball_speed_mps: 10.0
    max_unknown_s: 2.0

# Optional display names for the possession summary. The `players` stage prints which
# of the two kits it calls team_a (the darker, bluer, ... one).
# match:
#   team_a_name: "Team A"
#   team_b_name: "Team B"
"""


def onboarding_checklist(anchors_path: str | Path, config_path: str | Path) -> list[str]:
    """What is still missing before this clip can be run end to end."""
    missing: list[str] = []
    config_path, anchors_path = Path(config_path), Path(anchors_path)
    if not config_path.exists():
        missing.append(f"config not written: {config_path}")
    if not anchors_path.exists():
        missing.append(f"anchors not labelled: {anchors_path}")
    return missing
